### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by KendallDoesCoding** [karol-brejna-i/webpage-screenshot-action#60]
How to attach the image in README.md automatically whenever it runs?

**Comment by karol-brejna-i** [comment]
@KendallDoesCoding Could you please elaborate? This action's job is simply to take a screenshot. 
You could use some other actions/steps to upload the image (or to commit the image) to some repo...

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Could you please elaborate? This action's job is simply to take a screenshot. You could use some other actions/steps to upload the image (or to commit the image) to some repo...

Can you link an action to commit the image to the same repo.

**Comment by karol-brejna-i** [comment]
@KendallDoesCoding 

I am willing to create an example for such a use case. But I need to understand what we want to achieve better.
The overall schema for such a workflow would be:
- checkout a GitHub repo
- make a screenshot / other files modifications
- commit the changes to a specific branch
- push the changes to the repo
- optionally, create Pull Request for the branch

Could you confirm, that this is something close to what you want to achieve? Or something completely different?

Also, you write:

> "How to attach the image in README.md automatically whenever it runs?"

Could you be more specific? I see at least two ways of interpreting this sentence:

1. There is an existing README.md with an existing image link (i.e. `![my image}(/path/to/my/image.png)`) and we want the image content to be replaced with the new screenshot
2. There is a README.md where you want to add another entry that links to the new screenshot (new `![image](my_new_image.png)`)

Let me know, what it looks like in your case.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding
> 
> I am willing to create an example for such a use case. But I need to understand what we want to achieve better. The overall schema for such a workflow would be:
> 
> * checkout a GitHub repo
> * make a screenshot / other files modifications
> * commit the changes to a specific branch
> * push the changes to the repo
> * optionally, create Pull Request for the branch
> 
> Could you confirm, that this is something close to what you want to achieve? Or something completely different?
> 
> Also, you write:
> 
> > "How to attach the image in README.md automatically whenever it runs?"
> 
> Could you be more specific? I see at least two ways of interpreting this sentence:
> 
> 1. There is an existing README.md with an existing image link (i.e. `![my image}(/path/to/my/image.png)`) and we want the image content to be replaced with the new screenshot
> 2. There is a README.md where you want to add another entry that links to the new screenshot (new `![image](my_new_image.png)`)
> 
> Let me know, what it looks like in your case.

Yup.. This is exactly what I want to do.. I have a website with a table that lists YouTubers Birthdays - https://github.com/KendallDoesCoding/youtubers-birthdays... When, the table is updated, I want a screenshot to be clicked and uploaded to the repo, automatically. That screenshot will then embed in the README.md as a image.

**Comment by karol-brejna-i** [comment]
@KendallDoesCoding: Webpage Screenshot Action's sole purpose is to take screenshots. But your question shows, that the context in which it may be used is important. I prepared an example, that should help you figure out your case:
https://github.com/karol-brejna-i/webpage-screenshot-workflow-examples/

**Comment by KendallDoesCoding** [comment]
thank you so much. i will do this!
